%% Lab 1 - Coded BPSK Simulation
% Nicholas McKibben
% ECEn 770
% 2018-03-13

clear;
close all;

%% (1) Simulation
% Write a program that will simulate performance of the (7,4) Hamming code
% over a BSC channel with channel crossover probability p =
% Q(sqrt(2*Eb/N0)) and plot the probability of error as a function of Eb/N0
% in dB. On the same plot, plot the theoretical probability of error for
% uncoded BPSK transmission. Identify what the coding gain is for a
% probability of error Pb = 10e-5.

% Following Algorithm 1.4...
% (1) Fix Ec (typically Ec = 1). Compute R.
rng('default');
Ec = 1;
n = 7; k = 4;
R = k/n;
crossprob = @(N00) Q(sqrt(2*Ec/N00));
gammas = linspace(1,10,20); % signal-to-noise ratio
sigma2 = zeros(1,numel(gammas));
N0 = sigma2;
Pe = sigma2;
N = 8; % get this many errors

% Generator Matrix - (1.34) in book
G = [ 1 1 0 1 0 0 0;
      0 1 1 0 1 0 0;
      0 0 1 1 0 1 0;
      0 0 0 1 1 0 1 ];
H = [ 1 0 1 1 1 0 0;
      0 1 0 1 1 1 0;
      0 0 1 0 1 1 1 ];

% (2) for each signal-to-noise ratio gamma = Eb/N0
for ii = 1:numel(gammas)
    
    % (3) Compute N0 = Ec/(R*gamma) and sigma2 = N0/2
    N0(ii) = Ec/(R*gammas(ii));
    sigma2(ii) = N0(ii)/2;
    
    % (4) Compute the BSC crossover probability
    p = crossprob(N0(ii));
    
    % (5) do ... while
    nn = 0;
    nbits = 0;
    while nn < N
        % (6) Generate r as a vector of n random bits which are 1 with
        % probability p
        r = double(rand(1,n) > p);
        
        % (7) Increment the number of bits generated by k
        nbits = nbits + k;
        
        % (8) Compute the syndrome s = rH^T
        s = mod(r*H',2);
        
        % (9) If s ~= 0, determine the error location based on the column
        % of H which is equal to s and complement that bit of r
        if ~isequal(s,zeros(size(s)))
            fprintf('Found one!\n');
            
            %errpos = 
            
        end
    end
    
    % (13) Compute the probability of error
    Pe(ii) = nn/nbits;
end

%% (2) Hamming Code Simulation
% Repeat this for a (15, 11) Hamming code.